---
galaxy_info:
  description: Installs and Configures nodejs
  company: Traveloka
  license: MIT
  #min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
  - web

dependencies: []

