- name: Prepare Environment
  hosts: node1
  tasks:
    - name: Allow given host to connect
      shell: 
           cmd: |
               cat <<EOF
                 docker exec -it myjenkins bash
                 ssh-keyscan -H -t rsa 192.168.1.7 >> ~/.ssh/known_hosts
                 cat ~/.ssh/id_rsa.pub | ssh tegar.raharditya@192.168.1.7 'cat >> .ssh/authorized_keys'
               EOF
      become: yes

    - name: Check the testcafe installation
      shell: testcafe -v
      ignore_errors: True
      register: installed_testcafe
    
    - debug: var=installed_testcafe.stderr

    - name: Install testcafe
      shell: npm install -g testcafe
      when: "'not found' in installed_testcafe.stderr"
      become: true

    - name: Make sure docker is running
      service:
         name: docker
         state: started

    - name: Launch the docker container sonar postgresql
      docker_container:
          name: sonarpostdb
          image: postgres
          state: present
          published_ports: 
                 - 5432:5432
          env:
               POSTGRES_USER: sonar 
               POSTGRES_PASSWORD: sonar123., 
               POSTGRES_DB: sonar
      become: true

    - name: Launch the docker container mysonar
      docker_container:
          name: mysonar
          image: sonarqube
          state: present
          published_ports:
                 - 9000:9000
                 - 9092:9092
          env:
               SONARQUBE_JDBC_USERNAME: sonar 
               SONARQUBE_JDBC_PASSWORD: sonar123., 
               SONARQUBE_JDBC_URL: jdbc:postgresql://172.29.0.1:5432/sonar
      become: true

