---
# tasks file for nodejs-install

- block:
  - name: add apt key for nodejs
    # https://github.com/ansible/ansible/issues/9966#issuecomment-246373269
    shell:
      apt-key list | grep nodesource || \
        wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

  - name: add nodejs repository
    apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

  - name: install nodejs
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: no
    with_items:
      - "{{ nodejs_packages }}"

  - name: link node to nodejs
    file:
      src: "{{ nodejs_dir }}"
      dest: "{{ nodejs_link }}"
      state: link

  become: yes
  become_method: sudo
  tags:
    - nodejs-install

