 - name: Check the testcafe installation
   shell: testcafe -v
   ignore_errors: True
   register: installed_testcafe
    
 - debug: var=installed_testcafe.stderr

 - name: Install testcafe
   shell: npm install -g testcafe
   when: "'not found' in installed_testcafe.stderr"
   become: true

 - name: Check the junit-viewer installation
   shell: junit-viewer
   ignore_errors: True
   register: installed_junitviewer

 - name: Install junit-viewer
   shell: npm install -g junit-viewer
   when: "'not found' in installed_junitviewer.stderr"
   become: true
