---
    - name: Make sure docker is running
      service:
         name: docker
         state: started

    - name: pull an image
      docker_image:
         name: postgres
         tag: latest
  
    - name: Launch the docker container sonar postgresql
      docker_container:
          name: sonarpostdb
          image: postgres
          state: started
          published_ports: 
                 - 5432:5432
          env:
               POSTGRES_USER: sonar 
               POSTGRES_PASSWORD: sonar123., 
               POSTGRES_DB: sonar
      become: true

    - name: Launch the docker container mysonarqube
      docker_container:
          name: mysonar
          image: sonarqube
          state: started
          detach: true
          published_ports:
                 - 9000:9000
                 - 9092:9092
          env:
               SONARQUBE_JDBC_URL: "jdbc:postgresql://172.29.0.1:5432/sonar"
               SONARQUBE_JDBC_USERNAME: "sonar"
               SONARQUBE_JDBC_PASSWORD: "sonar123.,"
      become: true


    - name: Launch Artifactory
      docker_container:
        name: myartifactory
        image: tegarraharditya/artifactory
        state: started
        detach: true
        published_ports:
              - 18081:8081
      become: true


