---
    - name: Make sure docker is running
      service:
         name: docker
         state: started

    - name: pull an image
      docker_image:
         name: postgres
         tag: latest

    - name: Launch the docker container sonar postgresql
      docker_container:
          name: sonarpostdb
          image: postgres
          state: started
          published_ports: 
                 - "{{ postgres_ports }}"
          env:
               POSTGRES_USER: "{{ postgres_user }}" 
               POSTGRES_PASSWORD: "{{ postgres_pass }}" 
               POSTGRES_DB: "{{ postgres_db }}"
      become: true

    - name: Launch the docker container mysonarqube
      docker_container:
          name: mysonar
          image: sonarqube
          state: started
          detach: true
          published_ports:
                 - "{{ sonar_port_ext }}"
                 - "{{ sonar_port_int }}"
          env:
               SONARQUBE_JDBC_URL: "{{ sonar_jdbc_url }}"
               SONARQUBE_JDBC_USERNAME: "{{ sonar_user }}"
               SONARQUBE_JDBC_PASSWORD: "{{ sonar_pass }}"
      become: true


    - name: Launch Artifactory
      docker_container:
        name: myartifactory
        image: tegarraharditya/artifactory
        state: started
        detach: true
        published_ports:
              - "{{ artifactory_port }}"
      become: true


