---
galaxy_info:
  description: Installs pip
  company: Traveloka
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  categories:
  - packaging
  - system
dependencies: []
